### PR TITLE
MOMNG-138 Change Household text messages to voice

### PR DESCRIPTION
**Pull request by gsvr**

### CODE REVIEW

**Comment by gsvr** [comment]
@imsickofmaps Please review.

**Comment by imsickofmaps** [comment]
@gsvr copy needs updating as per: https://praekeltorg.atlassian.net/browse/MOMNG-138?focusedCommentId=15901&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15901

**Comment by gsvr** [comment]
@imsickofmaps :+1: ?

**Comment by imsickofmaps** [comment]
:+1:

**Pull request merged**
