### PR TITLE
Voice registration additional speech options

### PR DESCRIPTION
**Pull request by NicolaasDieBaas**
Search for `// TODO #63`
State 3B on latest voice flow
Requires three options: `father's`, `friend's`, `family member's`

### CODE REVIEW

**Comment by NicolaasDieBaas** [comment]
@gsvr please review

**Comment by gsvr** [comment]
@NicolaasDieBaas First pass done.

**Comment by NicolaasDieBaas** [comment]
@gsvr 2nd pass review plz

**Comment by gsvr** [comment]
:+1: (make sure to merge develop, though)

**Pull request merged**
