### PR TITLE
MOMNG-151 Update the language options to the 3 languages

### PR DESCRIPTION
**Pull request by NicolaasDieBaas**
All language lists should only be 3 languages for the pilot phase
English
Igbo
Pidgin
These languages are represented in this order across all scripts and recordings. Please note any technical updates should be pulled through across all IVR and USSD Public and HCW lines.
USSD HCW
state_msg_language
USSD Public
state_language
state_msg_language
IVR HCW
state_msg_language
IVR public
state_msg_language

### CODE REVIEW

**Comment by NicolaasDieBaas** [comment]
@imsickofmaps Please review

**Comment by imsickofmaps** [comment]
👍

**Comment by NicolaasDieBaas** [comment]
@imsickofmaps a quick double-check... I've assumed the language change might not be necessary for the following apps:
- train_ussd_public
- train_voice_public
- etc. (all the 'train_'-apps)
  Do they need to reflect the language option changes too, or is it ok for them to list the original five languages as options..?

**Comment by imsickofmaps** [comment]
@NicolaasDieBaas good catch, yes they do need just 3 too. Reviewing what's _not_ in a PR is hard to remember!

**Comment by NicolaasDieBaas** [comment]
@imsickofmaps good to land?

**Comment by imsickofmaps** [comment]
👍

**Pull request merged**
