### PR TITLE
MOMNG-207 Updates to the copy javascript state change

### PR DESCRIPTION
**Pull request by NicolaasDieBaas**
Hi WCL,
Janie Smit has picked up some minor discrepancies between what's in the POT files vs. what's in the final script for public state change USSD.
Please find the changes required in this google doc marked in red.
https://docs.google.com/document/d/1Ldydhj0fz2pnqlp-ynHiH6mRe9wuVo7hPJlv6HOvTbk/edit
Please can these copy changes be implemented in go-ussd_public.js app in https://github.com/praekelt/mama-ng-jsbox.

### CODE REVIEW

**Comment by NicolaasDieBaas** [comment]
@imsickofmaps @gsvr please review

**Comment by gsvr** [comment]
I would think you should update the training line(s) as well.

**Comment by NicolaasDieBaas** [comment]
I asked whether the public training line should be changed too but no answer yet...

**Comment by NicolaasDieBaas** [comment]
@gsvr apparently necessary changes to the training line will be identified and required as discovered. 👍 me if I can go ahead and land this issue

**Comment by gsvr** [comment]
That seems strange, but :+1: then.

**Pull request merged**
