### PR TITLE
Extend possible registration period to 10 months

### PR DESCRIPTION
**Pull request by smn**
Currently it's set to 9.

### CODE REVIEW

**Comment by smn** [comment]
@KaitCrawford @rudigiesler ready for review

**Comment by rudigiesler** [comment]
:+1:

**Comment by bruskiza** [comment]
@smn @rudigiesler this needs an updated voice file for the voice part doesn't it?
Any idea of what that file would be called?

**Comment by rudigiesler** [comment]
Looking quickly through the code, `PREBIRTH_MAX_WEEKS` defaults to `42`, suggesting that 10 months is an okay value. At the maximum of `42` weeks, with 2 messages per week, with `PREBIRTH_MIN_WEEKS` set to the default of `10`, it means that they will start at a sequence number of `2 * (42 - 10) = 64`. @bruskiza How many messages do we have in the message sets? Looking at QA, the max I can see is `66`, so starting at the max of `64` should mean that they get 2 messages or 1 week before moving over to the baby message set?

**Comment by bruskiza** [comment]
Thanks @rudigiesler, I'm talking about the IVR playback of the response.

If we add a "July 2014", there's no "July 2014" voice file in https://github.com/praekelt/hellomama-registration/tree/develop/registrations/static/audio/registration/eng_NG/*year*.mp3

Yes?

**Comment by rudigiesler** [comment]
@bruskiza This PR only addresses the USSD line, not the IVR line, so I don't think that that will be an issue (at least for the changes that I see in this PR)

**Comment by smn** [comment]
yeah this only touches USSD

**Pull request merged**
