### PR TITLE
MOMNG-141 - Adding pcm_NG translation

### PR DESCRIPTION
**Pull request by bruskiza**

### CODE REVIEW

**Comment by bruskiza** [comment]
@imsickofmaps @gsvr FYI.
Translation addition so merging once travis.

**Comment by imsickofmaps** [comment]
@bruskiza you also need to copy it here: https://github.com/praekelt/mama-ng-dockerconfig/tree/develop/qa/jssandbox_public_ussd and update: https://github.com/praekelt/mama-ng-dockerconfig/blob/develop/qa/jssandbox_public_ussd/jssandbox.yaml#L32

FYI @smn - I also suggested https://github.com/praekeltfoundation/ndoh-dockerconfig/pull/4#issuecomment-241730675 that we make this less manual in future - your thoughts?

**Comment by smn** [comment]
I'm happy to add things that make work easier. Let's run this one past @JayH5 again for when he has time (I know you tagged him on an earlier issue).

**Comment by bruskiza** [comment]
gents... any news on this?
Can we merge for now and refactor later?
Or would we rather refactor now?

@smn @JayH5 @imsickofmaps

**Comment by bruskiza** [comment]
@smn @JayH5 @imsickofmaps let me know what we do with this?
I'd say merge now, refactor later.

**Comment by smn** [comment]
please file a ticket for the refactoring and merge this.

**Comment by bruskiza** [comment]
Ticket filed here: https://praekeltorg.atlassian.net/browse/MOMNG-416

**Pull request merged**
